### ISSUE TITLE
Set up documentation missing context processor requirement

### ISSUE THREAD

**Issue by chielteuben** [ppetrid/yawd-admin#1]
Without 'django.core.context_processors.i18n' in your TEMPLATE_CONTEXT_PROCESSORS the admin will produce a KeyError when trying to display the menu.

**Comment by ghost** [comment]
Instead of documenting this I changed the code not to rely on the i18n processor; it doesn't make much sense to require it I believe. The change was included in 231da99. Thanks for the report.
