### ISSUE TITLE
Need more usability spoiler interface. (It must respond to the mouse hover).

### ISSUE THREAD

**Issue by pahaz** [ppetrid/yawd-admin#11]
I talk about model filed, that hiden in admin interface.

![Screen](https://f.cloud.github.com/assets/1394025/184147/e76c40a6-7ccd-11e2-8658-9382467cc02b.png)

**Comment by ghost** [comment]
hello, what do you mean respond to hover, can you elaborate a little? The design goal for hidden fieldsets is to open onclick, since a click event is possible in all sorts of screens and devices.

**Comment by pahaz** [comment]
I'm talking about action when you mouse hover over the spoiler. This may be a change in background color or another typical effect when you hover over the button.

**Comment by pahaz** [comment]
Also, clicking on the spoiler can change the direction of the arrow to the right of the name of the spoiler. A good example can be seen in the implementation of the spoiler in the django-grappelli.

**Comment by ghost** [comment]
I'll add this in the few next commits. After the latest updates you can also use the auto-generated affix left menu for lengthy pages, which is a far better option than collapsing fieldsets / inlines IMHO 
http://yawd-admin.readthedocs.org/en/latest/usage.html#side-navigation-for-change-forms
