### ISSUE TITLE
Allow customization of admin site name

### ISSUE THREAD

**Issue by volksman** [ppetrid/yawd-admin#12]
You have it as Django Administration in admin/includes/topnav.html

This should be customizable with a setting attribute or something.  It's a fairly large template so overriding it locally would likely be a pain to maintain.

**Comment by ghost** [comment]
I like the idea of a setting, it could be used to the logged_out_base template as well.

**Comment by volksman** [comment]
And login.html  :)

Would also be good to get rid of the welcome to yawdadmin on the login page.  Possibly another setting attr but I wouldn't put anything there myself.

**Comment by ghost** [comment]
yep i know, if we go the settings way there will be settings for both messages.

**Comment by volksman** [comment]
I didn't include a setting for a message.  Personally I think that makes things messy.  If you really want it and feel it's important I can add it with an option to leave it out.

**Comment by ghost** [comment]
yes please :) (e.g. see app.elorus.com)
We could surround the &lt;p&gt; element with something like 
{% if ADMIN_SITE_DESCRIPTION %}
to achieve the desired effect for your case when setting ADMIN_SITE_DESCRIPTION = None. The default value could still be "Welcome to the yawd-admin administration... etc". Is that ok?

**Comment by ghost** [comment]
Finally, we should document this feature before closing the issue. If you're not into it I'll do it, just commenting not to forget it.

**Comment by volksman** [comment]
Pushed with updated docs. :)

**Comment by ghost** [comment]
Thanks!
