### ISSUE TITLE
YawdAdmin breaks custom User model

### ISSUE THREAD

**Issue by volksman** [ppetrid/yawd-admin#14]
You define a form https://github.com/yawd/yawd-admin/blob/master/yawdadmin/forms.py that has fields hard coded.  This can't be for custom user models as the fields may not exist.  By defining this Django errors on basics like syncdb or shell.

**Comment by ghost** [comment]
Please see http://yawd-admin.readthedocs.org/en/latest/customize.html#my-account-view for information on how to change the form when using custom user models.

**Comment by ghost** [comment]
That's new functionality so maybe the documentation should elaborate on the subject, or we could change the title for "My account view" to "Integration with custom User models" or something. But it's working for sure, we run Elorus.com using custom user model!

**Comment by volksman** [comment]
The problem was that you import your form which tries to validate the fields.  I don't have a 'username' field in my custom model so it was failing (I assume you do in yours so it seemed OK).

Just move the import to after a test for the setting attr.  If it's not defined then run the import.

**Comment by ghost** [comment]
I can see your point. I wonder if something like 

ADMIN_USER_MODELFORM = getattr(settings, 'ADMIN_USER_MODELFORM', 'yawdadmin.forms.AdminUserModelForm')

would fix it (since we import the module from str later on). I think it's more elegant, as you note in your own comments. I've not tested it though yet, just sayin'..

**Comment by volksman** [comment]
You are absolutely correct.  Fixed and pushed.  Pull if/when you wish!  :)

**Comment by ghost** [comment]
Thanks, I appreciate that! Will close on pull.
