### ISSUE TITLE
Fieldsets with 'collapse' class is broken

### ISSUE THREAD

**Issue by Nabu-thinker-ru** [ppetrid/yawd-admin#19]
In my admin.py I have this
![capture](https://f.cloud.github.com/assets/5621752/1276765/4c8fa6be-2e92-11e3-8549-0d63ed4c89f1.PNG)
Yawd-admin just hide this fieldsets
![capture](https://f.cloud.github.com/assets/5621752/1276761/f6a2071a-2e91-11e3-8d66-9e5476dff394.PNG)
:(

**Comment by ghost** [comment]
Thank you very much for the report, I believe it should be ok now!
