### ISSUE TITLE
AttributeError on JSONDecodeError when setting up Analytics

### ISSUE THREAD

**Issue by chielteuben** [ppetrid/yawd-admin#2]
[JSONDecodeError](https://github.com/yawd/yawd-admin/blob/master/yawdadmin/views.py#L97) doesn't exist when [this](https://github.com/yawd/yawd-admin/blob/master/yawdadmin/views.py#L2) import succeeds as it's part of simplejson.

**Comment by ghost** [comment]
hello, which python version are u using? It seems this class was deprecated in newer versions (that introduced json instead of simplejson) abd a ValueError is raised instead. Let me dig into this a little bit more

**Comment by ghost** [comment]
With my current setup it seems ok now. Can you confirm it's working for you as well?

**Comment by chielteuben** [comment]
Confirmed. I really love the effort that went into this btw, by far the best django admin I've seen to date!

**Comment by ghost** [comment]
Thank you very much, nice to know you like it!
