### ISSUE TITLE
PopupModelAdmin inside another PopupModelAdmin

### ISSUE THREAD

**Issue by lerrua** [ppetrid/yawd-admin#21]
Hello!

One question, my application needs a `PopupModelAdmin)` inside another `PopupModelAdmin)` and i have this:

![popup_inside_popup](https://f.cloud.github.com/assets/154603/1604463/85b7aed6-53be-11e3-90b2-70501505b65d.png)

This is good anyway, but the clean solution would be like `modal_size = '900:300px'` or something better i guess...
Ouch! In this case CKEditor does not show the entire on modal.

What do you think? Is there anything that can help me?

**Comment by ghost** [comment]
I feel that the modal behavior is ok as it is, we could though provide a behavior like the one you describe (e.g. could the modal attribute be a dictionary? i.e. modal = {'width': 900, 'height': 300}) but I think it's not top priority plus we might figure out something that works on other devices as well.
As for the CKEditor, can this widget be configured to a percentage width of the page?

**Comment by lerrua** [comment]
Great! Dictionary is an excellent idea, if you want i can help it.

Yes, CKEditor can be configured to a percentage width. My bad.

**Comment by ghost** [comment]
if you think you can try something towards this direction it would be great. I'm not sure it can really help though since it's an iframe within an iframe.
