### ISSUE TITLE
js sorting language inlines

### ISSUE THREAD

**Issue by raphigaziano** [ppetrid/yawd-admin#23]
Hi!

I'm using yawd-admin together with your translations-app, just hacking something together to see how it goes.

I ran into a few problems, the first of which being that the inline forms for each language completely ignored the order they were assigned and simply stayed in alphabetical order (which was pretty annoying, i expected to have the site's default language first and instead had to select it each time i wanted to input something).

I tracked this issue down, it's caused by this bit of js right at the end of `yawd-admin.js`:

``` javascript
var ul = $('#language-codes');
if (ul.length) {
    ul.append(ul.children("li").detach().sort(function(a, b) {
        if (a.children[0].text > b.children[0].text) return 1;
            return -1;
    }));
}
```

Commented it out, and the ordering now works as i assumed it would. Since it seems targeted at integrating the translations app, and seeing that this app does order its querysets in a way that respect the values set in the admin, i don't really get why it's there. Coult it be some leftover from older versions ?

Just thought i'd mentionned it. I'll gladly submit a pull request if it turns out the snippet's not needed anymore, as i'd rather not override it myself in every project.

**Comment by ghost** [comment]
Hello, it seems this really is an old snippet that somehow was left there. I agree it must be removed and I'd appreciate it if you submitted this pull request. Please feel also free to contribute any opinions/bugs in regards to the integration with yawd-translations. Thanks for taking the time to bring this up, hope you like the apps.
