### ISSUE TITLE
'str' object has no attribute '_js' when trying to view the object permissions

### ISSUE THREAD

**Issue by chielteuben** [ppetrid/yawd-admin#3]
[Exception Location](https://github.com/yawd/yawd-admin/blob/master/yawdadmin/templatetags/yawdadmin_tags.py#L28)  
Django version: 1.4.2

**Comment by ghost** [comment]
Hello, can you please provide a little more info on the scenario this exception occurs? Which view are you referring to?

**Comment by chielteuben** [comment]
In this case when going to the auth/user page and trying to view the object permissions (obj_perms_manage_view from guardian).

**Comment by ghost** [comment]
Hello, I've installed django-guardian and commited a fix for this. Note that although the functionality is working, django-guardian templates are not designed for the yawd-admin html/css. I can see they support grappelli, you could file an issue there and request for yawd-admin templates as well.

Please confirm the latest master is working for you to close the issue.

**Comment by chielteuben** [comment]
It's working, thanks.
