### ISSUE TITLE
collectstatic failed!

### ISSUE THREAD

**Issue by CARocha** [ppetrid/yawd-admin#30]
Hi, when i run collectstatic in django 1.6 this fails, this says

Post-processing 'yawd-admin/css/admin.css' failed!

raise processed
ValueError: The file 'yawd-admin/img/gcons/cassete.png' could not be found with <pipeline.storage.PipelineCachedStorage object at 0xa4b5c2c>.

i used django-pipeline, django1.6.x and yawd-admin 0.7.0
is normal the file or imagen cassete.png no exist???

Cheers

**Comment by ghost** [comment]
Thanks for the report! It was a typo...
