### ISSUE TITLE
Can't select an id with raw_id_fields

### ISSUE THREAD

**Issue by rspt** [ppetrid/yawd-admin#31]
Hello,

I just installed yawd-admin and it's very nice (thanks for the work!).

I've a problem with the fancy box and the raw_id_fields.

When I click on the magnifiying glass next to a raw_id_field, this open the fancybox but I can't select directly the object that I want to populate the raw_id_field with the object id.

Thanks for looking at this "problem"

**Comment by ghost** [comment]
I also have this problem. It opens full django admin in fancy box instead of custom selector for ids.
I'll appreciate if someone tell me how to fix this problem.

**Comment by ghost** [comment]
@rspt I've found that in development version (master branch) this issue was fixed.

**Comment by rspt** [comment]
Ok thanks a lot for the information!

**Comment by rspt** [comment]
I close this issue due to the inactivity and seems the problem seems to be resolved.
