### ISSUE TITLE
MultiValueDictKeyError django 1.6.5

### ISSUE THREAD

**Issue by CARocha** [ppetrid/yawd-admin#34]
Hi, in version django1.6.5 i have error in inlines,
When yawd will support django 1.6? i use version 0.7

my error is when edit inline data :/

Cheers

**Comment by mwolff44** [comment]
You can copy new templates in admin/edit_inline in your personal template directory.
inline has changed in django 1.6

**Comment by CARocha** [comment]
ok excelents!
