### ISSUE TITLE
cannot login in the live demo using demo/demo

### ISSUE THREAD

**Issue by fabiocaccamo** [ppetrid/yawd-admin#39]

**Comment by michellemark** [comment]
The error message if you try to log in with demo/demo is

Please enter the correct username and password for a staff account. Note that both fields may be case-sensitive.

given this was first reported in March can you please change the password back to be demo / demo?

**Comment by namratab94** [comment]
Facing the same issue as above, can you please change it to demo/demo?

**Comment by michellemark** [comment]
I presume by the lack of response this is an abandoned project.. too bad it looks like it was nice
