### ISSUE TITLE
KeyError on new Analytics property/app with no data

### ISSUE THREAD

**Issue by chielteuben** [ppetrid/yawd-admin#8]
Django Version:     1.4.2
Exception Type:     KeyError
Exception Value:    'rows'
Exception Location:     [/yawdadmin/utils.py in get_analytics_data, line 98](https://github.com/yawd/yawd-admin/blob/master/yawdadmin/utils.py#L98)

As the title says, this happens when you add a property which has no visitor tracking data yet (api doesn't return what is expected).

**Comment by ghost** [comment]
Ok thanks for the report! I just commited a patch for this, tell me how it works for you. I have not an empty analytics account right now, hopefully this works and I don't need to create one :)

Today we reworked the list filters in changelist view by the way, does it work ok in your setup?

**Comment by chielteuben** [comment]
The patch works! Also, the list filter works beautifully :-)
